### ISSUE TITLE
Applying option have no effect

### ISSUE THREAD

**Issue by shbli** [aliascash/alias-wallet-archive#23]
Applying option on the wallet have no effect

**Comment by aliascash** [comment]
Can't change any options ('Options' menu on the left), unable to save when you hit OK or Apply. If you change a value and click 'Apply' or 'Ok' the value reverts to the default. Win 10 and beta-4

**Comment by shbli** [comment]
Issue fixed. Reopen with comments if you are facing the problem again. Should be good with a new upcoming build.

**Comment by shbli** [comment]
Hey @spectrecoin  you may try beta 5

https://www.dropbox.com/sh/ggybk70skjqy8e0/AAAI-58wHcwo_bfwkz0LlNm7a?dl=0

If you like to wait for the official release then feel free to do that. But we will appreciate you trying out beta 5 and let us know if it fixes the issues.

**Comment by ptownsimon** [comment]
**Options that still can't be changed (tested on 1.4 Win64 Beta 5):**
- Pay Transaction Fee
- Reserve
- Automatically Select Ring Size


**Options that CAN be changed but can't be changed to previous setting (since wallet startup) until after wallet restart:**
- Enable Staking
- Staking Donation
- Minimum Stake Interval
- Minimum Ring Size
- Maximum Ring Size
- Enable Secure Messaging
- Automatically Select Ring Size
- Thin Mode
- Thin Full Index
- Thin Index Window
- Minimize to the Tray Instead of the Taskbar
- Minimize on Close
- Unit to Show Amounts In
- Rows Per Page
- User Interface language (Didn't test since I don't want to mess with language, but most likely)

**Comment by shbli** [comment]
@ptownsimon thank you for this. just for future reference try to reopen the issue if it is still incomplete. but thank you I already did that now.

if an issue is closed. it won't be found by us and we may forget about it. Now I have seen your comment on my email and that way I noticed it.

**Comment by shbli** [comment]
@ptownsimon let me know if reserve balance in the newest version works as expected.

I'll compile a new beta and post a link here for beta 7

Here is beta 7: https://www.dropbox.com/sh/ggybk70skjqy8e0/AAAI-58wHcwo_bfwkz0LlNm7a?dl=0

**Comment by ptownsimon** [comment]
@shbli I tested this on 1.4.0 Beta 7 Win64
- Reserve Balance can now be edited
- Pay Transaction Fee can now be edited
- Automatically Select Ring Size can now be edited, but can't be changed back to previous setting until after wallet restart

Many options still can be changed, but need a wallet restart to change back to previous setting. Would this be a separate issue now?

I don't know how to reopen an issue.
