### ISSUE TITLE
1.4 b3: unable to unlock the wallet

### ISSUE THREAD

**Issue by Marvel63** [aliascash/alias-wallet-archive#25]
Trying to unlock my wallet with the same password I used with 1.3.5: got a message 'invalid passphrase'.
Checked 4 times if I use the right password, the answer is yes.

Don't hesitate to reach me out if any logs or screencast needed

**Comment by shbli** [comment]
Hi

This bug is reported and I’m working on it.

Go ahead and use the older wallet for now.

Cheers
Shbli

Sent from my iPhone

On May 25, 2018, at 6:02 AM, Marvel63 <notifications@github.com<mailto:notifications@github.com>> wrote:


Trying to unlock my wallet with the same password I used with 1.3.5: got a message 'invalid passphrase'.
Checked 4 times if I use the right password, the answer is yes.

Don't hesitate to reach me out if any logs or screencast needed

**Comment by shbli** [comment]
@Marvel63 There's beta 4 https://www.dropbox.com/sh/ez1dm51s6i2bcp4/AABfvJLLmfemNop0qBI093cla?dl=0

This is still going under review by Mandica and the team before publishing it but it fixes the above problem let me know if you feel like testing it. Otherwise wait for the announcement for it.

**Comment by Marvel63** [comment]
it works, good job guys
