### ISSUE TITLE
Remove "Generated but not accepted, Staked" from wallet transaction list

### ISSUE THREAD

**Issue by aliascash** [aliascash/alias-wallet-archive#9]
The 'Recent Transactions' pane in the wallet shows both accepted and 'not accepted' staked transactions. The same is the case for 'Transactions' tab. This should be changed so that ONLY the accepted staked transactions are shown.
<img width="368" alt="screen shot 2018-04-11 at 22 56 19" src="https://user-images.githubusercontent.com/22733129/38645449-fc94382e-3ddb-11e8-872f-93ce78d26d9b.png">
<img width="499" alt="screen shot 2018-04-11 at 22 56 30" src="https://user-images.githubusercontent.com/22733129/38645452-00d76a14-3ddc-11e8-8b10-257a13016ad2.png">

**Comment by aliascash** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Remove "Generated but not accepted, Staked" from wallet transaction list](https://trello.com/c/xFZh5EHq/7-remove-generated-but-not-accepted-staked-from-wallet-transaction-list)

**Comment by teknex** [comment]
With V3, generated but not accepted stakes are made distinguishable on the recent transaction list by showing them as orphans instead as stakes. Also the tooltip does now explain how a stake can become an orphan. Showing orphans is important for the user since having many orphans is a sign of a setup problem like bad wifi connection.
